WITH HOUT_SUB AS (
    SELECT
        DATE_FORMAT(DATETIME, '%H') AS HOUR
    FROM
        ANIMAL_OUTS
)
SELECT
    HOUR,
    COUNT(*) AS COUNT
FROM
    HOUT_SUB
WHERE 
    HOUR >= '09' AND HOUR < '20'
GROUP BY HOUR
ORDER BY HOUR;
