SELECT
    ED.ID,
    ED.GENOTYPE,
    PARENT_ED.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA ED
INNER JOIN
    ECOLI_DATA PARENT_ED
ON ED.PARENT_ID = PARENT_ED.ID
WHERE ED.GENOTYPE & PARENT_ED.GENOTYPE = PARENT_ED.GENOTYPE
ORDER BY ED.ID;